version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888"
      - "4317:18889"

  myapp1:
    image: ${DOCKER_REGISTRY-}myapp1
    build:
      context: .
      dockerfile: MyApp1/Dockerfile

  myapp2:
    image: ${DOCKER_REGISTRY-}myapp2
    build:
      context: .
      dockerfile: MyApp2/Dockerfile

